version: '1.0'

services:
  redis-1:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis-1
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: resize-img-api:1.0
    ports:
      - "4123:4123"
    environment:
      - PORT=4123
 
